run:
  timeout: 5m
  tests: true
linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - godox
issues:
  exclude-use-default: false
