// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-go/internal/ent/course"
	"lms-go/internal/ent/enrollment"
	"lms-go/internal/ent/group"
	"lms-go/internal/ent/organization"
	"lms-go/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// Where appends a list predicates to the GroupUpdate builder.
func (gu *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate {
	gu.mutation.Where(ps...)
	return gu
}

// SetOrganizationID sets the "organization_id" field.
func (gu *GroupUpdate) SetOrganizationID(u uuid.UUID) *GroupUpdate {
	gu.mutation.SetOrganizationID(u)
	return gu
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableOrganizationID(u *uuid.UUID) *GroupUpdate {
	if u != nil {
		gu.SetOrganizationID(*u)
	}
	return gu
}

// SetCourseID sets the "course_id" field.
func (gu *GroupUpdate) SetCourseID(u uuid.UUID) *GroupUpdate {
	gu.mutation.SetCourseID(u)
	return gu
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableCourseID(u *uuid.UUID) *GroupUpdate {
	if u != nil {
		gu.SetCourseID(*u)
	}
	return gu
}

// ClearCourseID clears the value of the "course_id" field.
func (gu *GroupUpdate) ClearCourseID() *GroupUpdate {
	gu.mutation.ClearCourseID()
	return gu
}

// SetName sets the "name" field.
func (gu *GroupUpdate) SetName(s string) *GroupUpdate {
	gu.mutation.SetName(s)
	return gu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableName(s *string) *GroupUpdate {
	if s != nil {
		gu.SetName(*s)
	}
	return gu
}

// SetDescription sets the "description" field.
func (gu *GroupUpdate) SetDescription(s string) *GroupUpdate {
	gu.mutation.SetDescription(s)
	return gu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableDescription(s *string) *GroupUpdate {
	if s != nil {
		gu.SetDescription(*s)
	}
	return gu
}

// ClearDescription clears the value of the "description" field.
func (gu *GroupUpdate) ClearDescription() *GroupUpdate {
	gu.mutation.ClearDescription()
	return gu
}

// SetCapacity sets the "capacity" field.
func (gu *GroupUpdate) SetCapacity(i int) *GroupUpdate {
	gu.mutation.ResetCapacity()
	gu.mutation.SetCapacity(i)
	return gu
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableCapacity(i *int) *GroupUpdate {
	if i != nil {
		gu.SetCapacity(*i)
	}
	return gu
}

// AddCapacity adds i to the "capacity" field.
func (gu *GroupUpdate) AddCapacity(i int) *GroupUpdate {
	gu.mutation.AddCapacity(i)
	return gu
}

// ClearCapacity clears the value of the "capacity" field.
func (gu *GroupUpdate) ClearCapacity() *GroupUpdate {
	gu.mutation.ClearCapacity()
	return gu
}

// SetMetadata sets the "metadata" field.
func (gu *GroupUpdate) SetMetadata(m map[string]interface{}) *GroupUpdate {
	gu.mutation.SetMetadata(m)
	return gu
}

// ClearMetadata clears the value of the "metadata" field.
func (gu *GroupUpdate) ClearMetadata() *GroupUpdate {
	gu.mutation.ClearMetadata()
	return gu
}

// SetUpdatedAt sets the "updated_at" field.
func (gu *GroupUpdate) SetUpdatedAt(t time.Time) *GroupUpdate {
	gu.mutation.SetUpdatedAt(t)
	return gu
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (gu *GroupUpdate) SetOrganization(o *Organization) *GroupUpdate {
	return gu.SetOrganizationID(o.ID)
}

// SetCourse sets the "course" edge to the Course entity.
func (gu *GroupUpdate) SetCourse(c *Course) *GroupUpdate {
	return gu.SetCourseID(c.ID)
}

// AddEnrollmentIDs adds the "enrollments" edge to the Enrollment entity by IDs.
func (gu *GroupUpdate) AddEnrollmentIDs(ids ...uuid.UUID) *GroupUpdate {
	gu.mutation.AddEnrollmentIDs(ids...)
	return gu
}

// AddEnrollments adds the "enrollments" edges to the Enrollment entity.
func (gu *GroupUpdate) AddEnrollments(e ...*Enrollment) *GroupUpdate {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return gu.AddEnrollmentIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (gu *GroupUpdate) Mutation() *GroupMutation {
	return gu.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (gu *GroupUpdate) ClearOrganization() *GroupUpdate {
	gu.mutation.ClearOrganization()
	return gu
}

// ClearCourse clears the "course" edge to the Course entity.
func (gu *GroupUpdate) ClearCourse() *GroupUpdate {
	gu.mutation.ClearCourse()
	return gu
}

// ClearEnrollments clears all "enrollments" edges to the Enrollment entity.
func (gu *GroupUpdate) ClearEnrollments() *GroupUpdate {
	gu.mutation.ClearEnrollments()
	return gu
}

// RemoveEnrollmentIDs removes the "enrollments" edge to Enrollment entities by IDs.
func (gu *GroupUpdate) RemoveEnrollmentIDs(ids ...uuid.UUID) *GroupUpdate {
	gu.mutation.RemoveEnrollmentIDs(ids...)
	return gu
}

// RemoveEnrollments removes "enrollments" edges to Enrollment entities.
func (gu *GroupUpdate) RemoveEnrollments(e ...*Enrollment) *GroupUpdate {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return gu.RemoveEnrollmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GroupUpdate) Save(ctx context.Context) (int, error) {
	gu.defaults()
	return withHooks(ctx, gu.sqlSave, gu.mutation, gu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GroupUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GroupUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GroupUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gu *GroupUpdate) defaults() {
	if _, ok := gu.mutation.UpdatedAt(); !ok {
		v := group.UpdateDefaultUpdatedAt()
		gu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gu *GroupUpdate) check() error {
	if v, ok := gu.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if _, ok := gu.mutation.OrganizationID(); gu.mutation.OrganizationCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Group.organization"`)
	}
	return nil
}

func (gu *GroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := gu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID))
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := gu.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
	}
	if gu.mutation.DescriptionCleared() {
		_spec.ClearField(group.FieldDescription, field.TypeString)
	}
	if value, ok := gu.mutation.Capacity(); ok {
		_spec.SetField(group.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := gu.mutation.AddedCapacity(); ok {
		_spec.AddField(group.FieldCapacity, field.TypeInt, value)
	}
	if gu.mutation.CapacityCleared() {
		_spec.ClearField(group.FieldCapacity, field.TypeInt)
	}
	if value, ok := gu.mutation.Metadata(); ok {
		_spec.SetField(group.FieldMetadata, field.TypeJSON, value)
	}
	if gu.mutation.MetadataCleared() {
		_spec.ClearField(group.FieldMetadata, field.TypeJSON)
	}
	if value, ok := gu.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
	}
	if gu.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.OrganizationTable,
			Columns: []string{group.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.OrganizationTable,
			Columns: []string{group.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if gu.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.CourseTable,
			Columns: []string{group.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.CourseTable,
			Columns: []string{group.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if gu.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.EnrollmentsTable,
			Columns: []string{group.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.RemovedEnrollmentsIDs(); len(nodes) > 0 && !gu.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.EnrollmentsTable,
			Columns: []string{group.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.EnrollmentsTable,
			Columns: []string{group.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gu.mutation.done = true
	return n, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMutation
}

// SetOrganizationID sets the "organization_id" field.
func (guo *GroupUpdateOne) SetOrganizationID(u uuid.UUID) *GroupUpdateOne {
	guo.mutation.SetOrganizationID(u)
	return guo
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableOrganizationID(u *uuid.UUID) *GroupUpdateOne {
	if u != nil {
		guo.SetOrganizationID(*u)
	}
	return guo
}

// SetCourseID sets the "course_id" field.
func (guo *GroupUpdateOne) SetCourseID(u uuid.UUID) *GroupUpdateOne {
	guo.mutation.SetCourseID(u)
	return guo
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableCourseID(u *uuid.UUID) *GroupUpdateOne {
	if u != nil {
		guo.SetCourseID(*u)
	}
	return guo
}

// ClearCourseID clears the value of the "course_id" field.
func (guo *GroupUpdateOne) ClearCourseID() *GroupUpdateOne {
	guo.mutation.ClearCourseID()
	return guo
}

// SetName sets the "name" field.
func (guo *GroupUpdateOne) SetName(s string) *GroupUpdateOne {
	guo.mutation.SetName(s)
	return guo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableName(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetName(*s)
	}
	return guo
}

// SetDescription sets the "description" field.
func (guo *GroupUpdateOne) SetDescription(s string) *GroupUpdateOne {
	guo.mutation.SetDescription(s)
	return guo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableDescription(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetDescription(*s)
	}
	return guo
}

// ClearDescription clears the value of the "description" field.
func (guo *GroupUpdateOne) ClearDescription() *GroupUpdateOne {
	guo.mutation.ClearDescription()
	return guo
}

// SetCapacity sets the "capacity" field.
func (guo *GroupUpdateOne) SetCapacity(i int) *GroupUpdateOne {
	guo.mutation.ResetCapacity()
	guo.mutation.SetCapacity(i)
	return guo
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableCapacity(i *int) *GroupUpdateOne {
	if i != nil {
		guo.SetCapacity(*i)
	}
	return guo
}

// AddCapacity adds i to the "capacity" field.
func (guo *GroupUpdateOne) AddCapacity(i int) *GroupUpdateOne {
	guo.mutation.AddCapacity(i)
	return guo
}

// ClearCapacity clears the value of the "capacity" field.
func (guo *GroupUpdateOne) ClearCapacity() *GroupUpdateOne {
	guo.mutation.ClearCapacity()
	return guo
}

// SetMetadata sets the "metadata" field.
func (guo *GroupUpdateOne) SetMetadata(m map[string]interface{}) *GroupUpdateOne {
	guo.mutation.SetMetadata(m)
	return guo
}

// ClearMetadata clears the value of the "metadata" field.
func (guo *GroupUpdateOne) ClearMetadata() *GroupUpdateOne {
	guo.mutation.ClearMetadata()
	return guo
}

// SetUpdatedAt sets the "updated_at" field.
func (guo *GroupUpdateOne) SetUpdatedAt(t time.Time) *GroupUpdateOne {
	guo.mutation.SetUpdatedAt(t)
	return guo
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (guo *GroupUpdateOne) SetOrganization(o *Organization) *GroupUpdateOne {
	return guo.SetOrganizationID(o.ID)
}

// SetCourse sets the "course" edge to the Course entity.
func (guo *GroupUpdateOne) SetCourse(c *Course) *GroupUpdateOne {
	return guo.SetCourseID(c.ID)
}

// AddEnrollmentIDs adds the "enrollments" edge to the Enrollment entity by IDs.
func (guo *GroupUpdateOne) AddEnrollmentIDs(ids ...uuid.UUID) *GroupUpdateOne {
	guo.mutation.AddEnrollmentIDs(ids...)
	return guo
}

// AddEnrollments adds the "enrollments" edges to the Enrollment entity.
func (guo *GroupUpdateOne) AddEnrollments(e ...*Enrollment) *GroupUpdateOne {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return guo.AddEnrollmentIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (guo *GroupUpdateOne) Mutation() *GroupMutation {
	return guo.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (guo *GroupUpdateOne) ClearOrganization() *GroupUpdateOne {
	guo.mutation.ClearOrganization()
	return guo
}

// ClearCourse clears the "course" edge to the Course entity.
func (guo *GroupUpdateOne) ClearCourse() *GroupUpdateOne {
	guo.mutation.ClearCourse()
	return guo
}

// ClearEnrollments clears all "enrollments" edges to the Enrollment entity.
func (guo *GroupUpdateOne) ClearEnrollments() *GroupUpdateOne {
	guo.mutation.ClearEnrollments()
	return guo
}

// RemoveEnrollmentIDs removes the "enrollments" edge to Enrollment entities by IDs.
func (guo *GroupUpdateOne) RemoveEnrollmentIDs(ids ...uuid.UUID) *GroupUpdateOne {
	guo.mutation.RemoveEnrollmentIDs(ids...)
	return guo
}

// RemoveEnrollments removes "enrollments" edges to Enrollment entities.
func (guo *GroupUpdateOne) RemoveEnrollments(e ...*Enrollment) *GroupUpdateOne {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return guo.RemoveEnrollmentIDs(ids...)
}

// Where appends a list predicates to the GroupUpdate builder.
func (guo *GroupUpdateOne) Where(ps ...predicate.Group) *GroupUpdateOne {
	guo.mutation.Where(ps...)
	return guo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GroupUpdateOne) Select(field string, fields ...string) *GroupUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Group entity.
func (guo *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	guo.defaults()
	return withHooks(ctx, guo.sqlSave, guo.mutation, guo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GroupUpdateOne) SaveX(ctx context.Context) *Group {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GroupUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (guo *GroupUpdateOne) defaults() {
	if _, ok := guo.mutation.UpdatedAt(); !ok {
		v := group.UpdateDefaultUpdatedAt()
		guo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guo *GroupUpdateOne) check() error {
	if v, ok := guo.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if _, ok := guo.mutation.OrganizationID(); guo.mutation.OrganizationCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Group.organization"`)
	}
	return nil
}

func (guo *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	if err := guo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID))
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, group.FieldID)
		for _, f := range fields {
			if !group.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != group.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := guo.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
	}
	if guo.mutation.DescriptionCleared() {
		_spec.ClearField(group.FieldDescription, field.TypeString)
	}
	if value, ok := guo.mutation.Capacity(); ok {
		_spec.SetField(group.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := guo.mutation.AddedCapacity(); ok {
		_spec.AddField(group.FieldCapacity, field.TypeInt, value)
	}
	if guo.mutation.CapacityCleared() {
		_spec.ClearField(group.FieldCapacity, field.TypeInt)
	}
	if value, ok := guo.mutation.Metadata(); ok {
		_spec.SetField(group.FieldMetadata, field.TypeJSON, value)
	}
	if guo.mutation.MetadataCleared() {
		_spec.ClearField(group.FieldMetadata, field.TypeJSON)
	}
	if value, ok := guo.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
	}
	if guo.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.OrganizationTable,
			Columns: []string{group.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.OrganizationTable,
			Columns: []string{group.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if guo.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.CourseTable,
			Columns: []string{group.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.CourseTable,
			Columns: []string{group.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if guo.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.EnrollmentsTable,
			Columns: []string{group.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.RemovedEnrollmentsIDs(); len(nodes) > 0 && !guo.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.EnrollmentsTable,
			Columns: []string{group.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.EnrollmentsTable,
			Columns: []string{group.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Group{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	guo.mutation.done = true
	return _node, nil
}
